project:
  type: website
  output-dir: docs

website:
  title: "Zoe Bourne Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - portfolio.qmd
      - href: https://drive.google.com/file/d/1JNHaiyPBPztwITgg5GODKrFhRBGgyUSX/view?usp=sharing
        text: Resume
      - featured_paper.qmd
      - featured_story.qmd
      - analysis.qmd
      
  page-footer: 
    left: "Copyright 2022, Testy R. Testman" 
    right: 
      - icon: github
        href: https://github.com/
      - icon: twitter 
        href: https://twitter.com/
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true