project:
  type: website
  output-dir: docs

website:
  title: "Zoe Bourne Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - portfolio.qmd
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



