---
title: "Featured Paper"
editor: visual
---

**Introducing the Paper**

The following paper was written for Ethics and the Legal Environment, an undergraduate business course offered at George Washington University. Specifically, the paper was my final exam where I had to discuss a case assigned at random through the lenses of utilitarianism, denontology, Aristotelian logic, and ethics of care. This case surrounded the hypothetical company, Evergreen Investment. Senior partner, Richard Alpert, was set in his decision to promote Daniel Faraday. But when Alptert inconspicuously discovers that Faraday is illegally taking Adderall, Alpert has to decide who will be given the promotion.

***Evergreen Enhancement - Zoë Bourne, 4101W-13***

**Step One: Frameworks**

Richard Alpert, senior partner at Evergreen Investment, is trying to decide whether to promote Charlie Pace, the first-choice candidate, over runner-up, Daniel Faraday, after unintentionally learning Pace takes off-label Adderall to improve his focus and performance. Alpert ultimately has a choice at hand, should he promote his preferred candidate even after finding out this information? To aid in this process and to fully understand the consequences of the choice, the following frameworks can be applied. 

*Utilitarianism*

The consequences of this case remain substantial considering that if information about Pace's Adderall use gets out, it could pose many difficulties, and create a negative outcome for Alpert, Pace, and the company. Under favorable conditions, in this case, keeping Pace's Adderall use within the company and Pace not losing access to his Adderall, the company is likely to see favorable results if Pace is promoted to managing VP. Pace is known amongst the company as one of the rising stars and if he can translate these results into tangible growth, the company will thrive as a result. So with the promotion of Pace, it is likely that the company, Pace, and Alpert will be benefitted from this promotion. It is important to note that the company's employees may be neutrally to negatively impacted by this promotion. Given that Pace's performance is being artificially enhanced by a stimulant that he lied to obtain, he is likely to expect the employees under him to perform exceptionally long hours and calmly deal with the job's stress, two things that the drug aid him in doing. Without taking Adderall, employees may fall short of unrealistically high expectations, harming morale and performance as a result. This promotion can also be deemed risky, given Pace can no longer obtain Adderall or he transitions to other stimulants, such as cocaine, if his tolerance for the drug becomes too high. 

Looking at the case's implications on higher and lower pleasures, if Alpert chooses to promote Pace, he is compromising the higher pleasures surrounding moral sentiments including justice, honesty, and fairness. Knowing that Pace illegally obtained Adderall by lying to a psychiatrist, if Alpert withheld this information and did not consider these facts in his decision, Alpert would not be upholding fairness while failing to act along with what is just. Promoting Pace would be rewarding him for the illegal behavior he is engaged in, failing to uphold higher pleasures. And if word that these higher pleasures are intentionally not being upheld, employees may lose their faith and trust in Evergreen Enhancement

*Kantian/Deontological*

In overhearing Pace explain to a fellow employee the benefits of taking Adderall to improve work performance, Alpert overheard him say how he lied about his symptoms to get prescribed Adderall from a psychiatrist. Lying to or misleading a psychiatrist with the intent to obtain a drug that one otherwise wouldn't be prescribed is illegal. Given that the law severely punishes the behavior that Pace is engaged in, it can be easily deemed ethically unacceptable However, it is unknown by the public that Alpert is aware Pace takes Adderall. So in theory, if Alpert plead ignorance, his reputation would be safe. However, if Alpert did this, he would be lying to others around him, an act that is also deemed morally impermissible. If Alpert ignored what he learned about Pace in the decision-making process, he would be being dishonest with himself and the company. Dishonesty is generally frowned upon, and practicing dishonesty is doing a disservice to the greater community by restricting the flow of vital and circumstance-changing information.

*Virtue Ethics/Aristotelian*

If Alpert was to promote Pace to managing VP, as he originally wanted, he might feel conflicted and guilty by the ultimate decision. After taking into account the means Pace took to obtain the Adderall and the competitive edge it gives him over other employees, feelings of deceitfulness and doubt, two vices that may cloud Alpert's decision, would likely leave his conscience unclear. However, if Alpert were to ultimately not care about Pace illegally obtaining Adderall and recommending it to other employees, this would reflect poorly on Alpert's character, showing him as a man who ultimately rewards illegal behavior. If instead, Alpert took this as an opportunity to reflect on his original decision and choose Faraday over Pace, he would be developing virtue by not rewarding illegal behavior. However, it is important to note the law does not determine morality and Alpert must carefully consider the benefits of taking Adderall, including improved focus and concentration, to the downsides, promoting a potentially toxic workplace, and supporting illegal methods of obtaining an amphetamine.

One thing that is important to note is that Alpert is in a unique position to confront Pace rather than make this decision knowing the information he accidentally obtained. In this way, the uncertainty of whether or not Pace should be promoted, given he illegally takes Adderall, can open the door to an honest conversation about Alpert's concerns, the pressures of the industry, and other potential ways of coping with the stress. Confronting the uncertainty of the case at hand, rather than trying to ignore or justify it, will potentially allow Alpert to reach a decision he is happy and more confident with. Ultimately, this conversation provides an opportunity for Alpert and Pace to do some good, making appositive out of a negative, and approach the issue in a caring and compassionate way. Creating a safe space for Pace and Alpert would allow the natural hierarchal structure of the organization to be re-imagined, building further trust and transparency among two people with different positions within the group.

*Ethics of Care*

Alpert must look at the relationships and possible stakeholders impacted if he were still to promote Pace. The stakeholders, in this case, include but are not limited to, Pace, Daniel, and other employees, the company, the greater finance industry, and society at large. If Alpert decides to promote Pace over Faraday, his relationship with Pace will certainly be strengthened. Pace would likely view Alpert as a trusted superior who saw and rewarded his hard work, dedication, and sizeable contribution to the company. Pace would overall be pleased with the promotion and may be further incentivized to work harder and produce even greater results. The company would likely be pleased with the promotion of Pace over Faraday as well. Alpert notes Pace's work as "brilliant," praising him for the sizable clients he has brought to the company while outperforming others on his level. If promoted, Pace would likely apply his innovative tactics in his new position; but this time, having a wider reach and larger positive impact on the company. If his tactics prove successful in the role of managing VP, the company will likely see increased profits and growth. Employees are likely to be happy for Pace and supportive of the promotion, if familiar with him and his previous work. However, if the employees of Evergreen Enhancement or the public find out that one of the company's top employees was promoted by Alpert, knowing he took off-label Adderall, it is likely these relationships would be taxed as a result. To employees, this message rewards a toxic culture that values constant productivity and artificially enhances one's cognitive ability through illegal means to get ahead. 

**Step Two and Three: Explore Alternative Solutions and** **Improve Trade-offs**

*Promote Pace*

Alpert can proceed with his initial plan to promote Pace despite what he learned after overhearing the news that Pace takes off-script Adderall. Pace is one of the top-performing employees at the firm and taking Adderall gives him a boost in performance and focus. However, there are many risks that come with promoting Pace to managing VP including the fact that Pace obtained the drug illegally, might lose access to the drug one day, and after building up a tolerance to the drug might move onto a stronger stimulant.

With these risks in mind, Alpert can attempt to offset them and the unpredictable nature of Pace's Adderall use by having an honest conversation with Pace. This conversation can potentially help Pace express his concerns, why he turned to Adderall, and teach Pace healthier ways of coping with stress.

*Promote Faraday*

The obvious alternative to promoting Pace is to promote the second runner up for the position, Faraday. According to Alpert, Faraday is also very qualified for the job and an extremely hard worker given his humble roots in Oklahoma. Faraday's drive, which led him to the position he currently works in, makes him a likely candidate that will thrive in the role. However, promoting Faraday might bring about some confusion amongst employees and Pace. Pace has brought larger clients to the firm and is known for his elite education and background, and with this, people will likely question the ultimate choice.

To address these trade-offs, Alpert can discuss with Pace why he ultimately decided to promote Faraday. This discussion can help address the questions and concerns brought as a result of this final decision. Alpert can also set up an announcement stating that Faraday has been promoted. This announcement can include Faraday's past achievements and his suitability for the role.

*Outside Hire*

Instead of having to decide between Pace and Faraday, Alpert can instead fill the position with an outside hire. This move eliminates the need for Alpert to choose between the two candidates and allows him the flexibility to search through a virtually endless pool of candidates. But similar to the first alternative, not only will employees question why Pace did not receive the promotion, employees may ask why no one in the company received the promotion. Hiring from the outside may discourage employees, making them think there are limited opportunities for growth within the company.

To ease employee concerns, the company can make sure to be clear when promotion opportunities are available within the company. If the company makes sure to strongly consider internal promotions instead of external hires, employees will see one another move up throughout their careers. The company can also invest in their employees, offering to fund master's degrees and other certificates to make their employees more competitive within the field. 

*Expand the Scope of Work for more than One Employee*

Alpert can also consider distributing the work typically given to the managing VP to two employees. By splitting up the work typically assigned to the managing VP, increasing the pay, and maybe changing the employees' original titles, this move allows two employees to be promoted other than one employee receiving a large promotion. This choice allows Alpert not to have to choose between Pace and Faraday, and instead, he can distribute the responsibility of managing VP between both the men. However, this alternative does pose some downsides. Expanding the responsibility of two people, from what was initially a separate role, could easily overwhelm Pace and Faraday, given they are performing the job of one and a half people. Part of the reason Pace takes Adderall in the first place is to deal with the daily stresses of the job, and this move is not likely to positively contribute to this. Splitting up the role of one job may also create some confusion and inefficiencies if the two men in this role do not properly communicate with each other.

To help prevent any possible confusion or communication errors with this untraditional move, Alpert can make sure to split the responsibilities most naturally in a way where the two separate roles can be viewed as two different jobs. Finding natural splits in the job will help Pace and Faraday expand their responsibilities in a way that seems logical and natural. Alpert would also have to clearly communicate the new move to divide to positions and make sure the two men set times, at least once a week, to meet with each other and discuss their progress and long-term goals in the role.

**Step Four: Recommendations**

Before making a choice, it is vital that Alpert sit down with Pace and have an honest conversation about his Adderall use. Instead of discretely knowing this information, Alpert can be honest that he overheard what Pace was discussing, setting the grounds to an open and honest conversation. With this conversation, Alpert can state his potential concerns on promoting Pace and possibly point him towards healthier ways of coping with stress that arises from the job such as therapy.

After discussing with Pace, Alpert should open the job up to external hires. Before making the application live for others to apply, Alpert should take the time to notify staff he sees as a good fit to apply. Opening up the application pool to external hires will allow Alpert to see other candidates that may, in turn, end up being a better fit than Pace and Faraday. Taking this step, it is important that Alpert and the other executives at the firm make sure they are investing in their employees to promote their growth and success within the firm and the industry at large.

If, after looking at the value brought by external candidates. Alpert still wants to promote someone within the firm, he is at liberty to do this. Opening the candidacy pool simply gives Alpert more time to make his decision and provides him with more candidates to choose from.

With this recommendation, there are two things I feel are important for the company to address and implement with the final recommendation. First, the company should develop a very clear drug policy. In this policy, there should be a list of the drugs that are not permitted for employees to take and what to do if someone is found taking one of the drugs illicitly. This is standard with most companies and will help clearly settle disputes like this in the future. With making this policy known throughout the company, knowing the culture of the finance industry in general, it is important that Evergreen Enhancement provides resources for people to properly deal with stress or drug abuse. In Pace's case, he obtained the drug from a psychiatrist, so he could dispute claims and say the drug is for ADHD. Pace took this course of action due to the stresses of the job that are oftentimes needed to remain competitive in the field. And while it is out of the control of Alpert or Evergreen Enhancement to change the culture of the finance industry, they do have the power to foster a culture within the firm that promotes healthy and sustainable growth. The company can do this by changing or creating a mission statement and company values that evoke these goals. Additionally, expanding the staff to diffuse responsibility or provide more personal time off can also help elevate some of the daily stresses of the job.

**Step Five: Preparing the Protagonist**

In order to implement the following recommendations, Alpert must work with the other executives to discuss drug usage within the company and ways to prevent this from occurring. The other executives then can make the final decision as to add more time off, change the company mission statement, etc. It is then up to Alpert to talk with Pace and open up the job of managing VP to the public.

The nature of drug usage and how it plays into the finance industry is a very delicate subject. With this in mind, Alpert must prepare himself if the conversation with Pace doesn't go as planned. Pace could become angry, lose trust in the company, or feel like he is being attacked when Alpert discusses this topic with him. Alpert, in turn, must make sure he approaches the conversation from a place of support since it ultimately does affect his work and his performance. If this still makes Pace upset, Alpert must be prepared for the worst-case scenario being, Pace leaves the company. If this occurs, Alpert should still proceed with the recommendations of opening up the position of managing VP to the public. Alpert would then also need to open Pace's old position to the public as well. Alpert must also prepare for a limited applicant pool. If Alpert does not get the turnout he wants for the position, he may be stuck with his original choice of Pace and Faraday.
