---
title: "Featured Story"
editor: visual
---

**The Evolution of Police Accountability Tactics in Washington D.C**

WASHINGTON - The Angela Davis poster looked down upon Nee Nee as she sat in the center of the screen. Her voice was strained from sleepless nights fighting for the students of Howard University as she drew in her breath.

"I have been assaulted by the police, but it's their power and authority with a gun that they are able to assault me," said Nee Nee Taylor, co-conductor of Harriet's Wildest Dream. "And even when I make a complaint, which I have made a complaint, the disciplinary action doesn't get to me what actually happened. They just say your complaint was taken and disciplinary action was taken and they are going to get more training."

Flashing between screens, the public hearing for Washington D.C. residents garnered both support and criticism for the proposed amendment act to expand the rights of Washington's Office of Police Complaints. Attendees stipulated the specific terms of the amendment which aims to establish a public database for officer disciplinary records, expand the authority and capabilities of many positions within the committee and change the office's name to the Police Accountability Commission.

When an individual in Washington has experienced an alleged incident of police misconduct, victims and witnesses can submit an online complaint form through the Office of Police Complaints. When filing a case, an individual must input medical and incident information, contact information and known information about the officer.

Washington's Office of Police Complaints is an independent body that collects and investigates citizen complaints against the Metropolitan Police Department. The board received 841 complaints in 2020, making it the fourth consecutive record year for the number of complaints received by the department. For the 490 complaints that launched a formal investigation in 2020, the average investigation time was 95 days.

Washington was the first city in the United States to establish a Civilian Complaint Review Board due to the city's high rates of violence between the police and Black Washington residents. Formed in 1948, the board was known to be "largely ineffective" and was dissolved in 1965.

The Civilian Complaint Review Board was later re-established in 1980. But like its predecessor, the board was often criticized for being inefficient and underfunded. On average, the board received "approximately 500 complaints a year" but was "only able to dispose of about one hundred," according to the Human Rights Watch. As the Civilian Complaint Review Board struggled to keep up with incoming complaints, MPD hiring standards decreased throughout the decade. In 1989 and 1990, a hiring mandate was instated requiring the MPD to hire 1,500 officers per year to combat the city's crack cocaine epidemic.

The small police applicant pool was met with insufficient background checks and hiring managers that disregarded physical and psychological exam results to meet the department's hiring quota.

Police recruits from 1989 to 1990 were funneled into the police force, with it being reported that "some rookies did not even know the proper way to handcuff suspects," according to the Washington Post. From the hiring spree of 1989 and 1990, "one of every 14 officers hired" had been arrested during or after their time in the police force.

The board's inefficiencies were highlighted in the 1994 case Cox v. District of Columbia. After sustaining permanent scarring and injuries inflicted by two MPD officers, James Douglas Cox's complaint submitted to the Civilian Complaint Review Board did not get processed. The U.S. Court of Appeals found that the District of Columbia showed "deliberate indifference" towards the constitutional rights of Cox. The court claimed that the city government "made a conscious choice to close its eyes and cover its ears to the clamor of the complaints of police brutality" resulting in complaints filed with the Civilian Complaint Review Board being "nothing more than nullities."

1995 marked Washington's worst financial crisis in the past 120 years with the district's deficit reaching \$722 million, according to former D.C. Mayor Marion Barry. The lack of sufficient funds coupled with the board's inability to process complaints promptly was used as a justification for the board's closure. However, the D.C. Council reallocated the funds from the Civilian Complaint Review Board to MPD branches throughout Washington.

Following the Civilian Complaint Review Board's closure, the city lacked an independent review board for police misconduct for six years. The MPD faced a police force that was ill-equipped to properly respond to crime and de-escalate potentially violent situations. According to The Washington Post, "75 percent of the District officers who used their weapons in 1996 failed to meet the District's basic firearms standards for using the Glock semiautomatic handgun." Throughout the 1990s, Washington had the highest police shooting deaths per capita out of any major U.S. city. However between 1994 and 1998, 87% of the force used by officers was defined as justified. The MPD classified officer use of force as justified when an officer had "reasonable cause" to believe "an attacker could cause 'death or serious bodily injury," according to a Washington Post report. The Office of Police complaints reopened in January 2001 and received 310 formal complaints during its first fiscal year. Over the past 20 years, the number of complaints received by the Office of Police Complaints has steadily increased.

Graph indicating total complaints (informal complaints and filed complaints) and total formal complaints (filed complaints) in the District of Columbia by Zoë Bourne

"It starts with leadership and it starts with staffing as well," said Nykisha Cleveland, public affairs specialist at the Office of Police Complaints. "A lot of policies and procedures have been put in place so that what happened back in 1995 and before will not happen again."

Annual reports published by the Office of Police Complaints provide the public and legislators with quantitative data on officer and victim demographics and the type of misconduct that occurred. In 2020, the Office of Police Complaints reported that 91% of the department's use of force cases were against Black residents while making up 43.9% of the population.

The MPD declined to participate in an interview on the department's current protocol for officers under investigation, police accountability tactics and standard procedure for de-escalation.

"MPD officers are required by policy to intervene if they observe fellow officers using excessive force and to report if an officer is engaging in misconduct" said Alaina Gertz, Public Affairs Specialist at the MPD, through email.
