---
title: "Portfolio"
---

### Work Samples Journalistic Work

##### [D.C. Mayoral Candidate, Robert White's, Criminal Justice Campaign](https://www.dropbox.com/s/xy4zxeyxlis3mdy/D.C.%20Mayoral%20Candidate%2C%20Robert%20White%E2%80%99s%2C%20Criminal%20Justice%20Platform%20.pdf?dl=0)

| Written in the end of November, this story highlights key components of Robert White's Criminal Justice Campaign in his run for mayor.

##### [Ethnically Targeted Hate Crimes Increase 147% Since Last Year, but These Numbers Miss a Large Part of the Story](https://www.dropbox.com/s/y7e6p2ixs51r10y/Ethnically%20Targeted%20Hate%20Crimes%20Grew%20147%20Percent%20Since%20Last%20Year%2C%20but%20these%20Numbers%20Miss%20a%20Large%20Part%20of%20the%20Story.pdf?dl=0)

| Reporting on the effect that COVID-19 had on Asian communities and other communities of color in America, this story highlights the under reporting of hate crimes throughout the District of Columbia and the United States as a whole.

##### [The Psychological Effects of Imprisonment Have Long Proceeded DOJ Reports on D.C. Jail Conditions, Experts Say](https://www.dropbox.com/s/znncb48m9tgharj/The%20Psychological%20Effects%20of%20Imprisonment%20Have%20Long%20Preceded%20DOJ%20Reports%20on%20D.C.%20Jail%20Conditions%2C%20Experts%20Say.pdf?dl=0)

| After the DOJ was prompted to investigate D.C. Jail Conditions, following the January 6th Capitol Attacks, this story highlights that jails conditions have long been reported by the jails predominately Black population.
